from typing import Dict, Any
import logging

logger = logging.getLogger(__name__)


def generate_threat_report(
    ip: str,
    correlated: Dict[str, Any],
    risk: Dict[str, Any]
) -> str:
    """
    Generate AI-powered threat attribution report
    Currently returns structured placeholder - will be enhanced with Gemini 2.5 Pro
    """
    
    context = correlated.get("context", {})
    categories = correlated.get("categories", [])
    evidence = correlated.get("evidence", {})
    
    # Build structured report
    report_lines = []
    
    # Threat Assessment
    report_lines.append("## Threat Intelligence Summary")
    report_lines.append("")
    
    if risk["score"] >= 60:
        report_lines.append(f"⚠️ **MALICIOUS**: This IP address ({ip}) exhibits suspicious behavior with a risk score of {risk['score']}/100.")
    elif risk["score"] >= 40:
        report_lines.append(f"⚡ **SUSPICIOUS**: This IP address ({ip}) shows concerning patterns with a risk score of {risk['score']}/100.")
    else:
        report_lines.append(f"✓ **BENIGN**: This IP address ({ip}) appears relatively safe with a risk score of {risk['score']}/100.")
    
    report_lines.append("")
    
    # Threat Categories
    report_lines.append("### Threat Classification")
    if categories:
        for cat in categories:
            report_lines.append(f"• {cat}")
    else:
        report_lines.append("• No significant threats identified")
    report_lines.append("")
    
    # Geolocation & Attribution
    report_lines.append("### Attribution & Context")
    report_lines.append(f"• **Location**: {context.get('city', 'Unknown')}, {context.get('country', 'Unknown')}")
    report_lines.append(f"• **Organization**: {context.get('org', 'Unknown')}")
    report_lines.append(f"• **ASN**: {context.get('asn', 'Unknown')}")
    if context.get("hostname"):
        report_lines.append(f"• **Hostname**: {context.get('hostname')}")
    report_lines.append("")
    
    # Technical Evidence
    report_lines.append("### Technical Indicators")
    
    abuse = evidence.get("abuseipdb", {})
    if abuse.get("total_reports", 0) > 0:
        report_lines.append(f"• **Abuse Reports**: {abuse.get('total_reports')} reports with {abuse.get('confidence_score')}% confidence")
    
    vt_evidence = evidence.get("virustotal", {})
    malicious = vt_evidence.get("malicious", 0)
    suspicious = vt_evidence.get("suspicious", 0)
    if malicious > 0:
        report_lines.append(f"• **VirusTotal Detections**: {malicious} engines flagged as malicious")
    if suspicious > 0:
        report_lines.append(f"• **Suspicious Activity**: {suspicious} engines flagged as suspicious")
    
    reputation = vt_evidence.get("reputation", 0)
    if reputation != 0:
        rep_label = "positive" if reputation > 0 else "negative"
        report_lines.append(f"• **Reputation Score**: {reputation} ({rep_label})")
    
    tags = vt_evidence.get("tags", [])
    if tags:
        report_lines.append(f"• **Threat Tags**: {', '.join(tags[:5])}{'...' if len(tags) > 5 else ''}")
    
    report_lines.append("")
    
    # Recommendations
    report_lines.append("### Recommended Actions")
    if risk["score"] >= 60:
        report_lines.append("• 🔴 **BLOCK** this IP immediately in firewall rules")
        report_lines.append("• 🔍 Review logs for any connections from this IP")
        report_lines.append("• 📊 Monitor for related IOCs and lateral movement")
        report_lines.append("• 🚨 Consider triggering incident response procedures")
    elif risk["score"] >= 40:
        report_lines.append("• 🟡 **MONITOR** this IP closely for suspicious activity")
        report_lines.append("• 🔍 Review connection logs and access patterns")
        report_lines.append("• 🛡️ Implement rate limiting if applicable")
    else:
        report_lines.append("• ✓ No immediate action required")
        report_lines.append("• 📝 Continue standard monitoring procedures")
    
    report_lines.append("")
    report_lines.append("---")
    report_lines.append("*This report is generated by TICE AI Engine. For AI-enhanced analysis, configure Gemini 2.5 Pro API key.*")
    
    return "\n".join(report_lines)